### ISSUE TITLE
Need image file for hp956bx4547

### ISSUE THREAD

**Issue by caaster** [sul-dlss/piano-rolls#2]
(From Craig) Hi Tony,

Druid hp956bx4547 has some strange problems, so you should give me a copy of the image so I can study why the performance is so strange (one problem seems to be a large tear near the end, but there are other strange things happening as well, probably the score is transposed, maybe related to what is happening at the end of the roll).

https://supra.stanford.edu/uv/?id=hp956bx4547

https://supra.stanford.edu/drift/?druid=rr990ym0199

<img width="1428" alt="Screen Shot 2019-11-04 at 10 28 45 PM" src="https://user-images.githubusercontent.com/3210225/68345702-d36e1700-00a6-11ea-8347-b36e4117437d.png">

**Comment by calavano** [comment]
Image uploaded to CCRMA
