### ISSUE TITLE
Re-tag 7 objects in "General" as "Test"

### ISSUE THREAD

**Issue by caaster** [sul-dlss/piano-rolls#9]
See #5 for appropriate context.

See column D for roll type and manufacturer -- there are 9 rolls that DO NOT contain this information. 
https://docs.google.com/spreadsheets/d/1ihmN4hMG3SN0cgovp1PQd_Ih5A3rkYqpgxBvTKfHfH0/edit#gid=1422407229

**Comment by calavano** [comment]
2 have had the tags changed, 7 of the remaining are test rolls and will need to be re-scanned.
